# Generated by Django 4.0.10 on 2023-09-27 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_rename_cover_contactmessage_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactmessage',
            old_name='image',
            new_name='cover',
        ),
    ]
