# Generated by Django 4.0.10 on 2023-09-15 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_destination_cover'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='destination',
            options={'permissions': [('special_status', 'Can read all books')]},
        ),
    ]
