# Generated by Django 4.0.10 on 2023-09-15 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0004_alter_destination_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='destination',
            options={'permissions': [('special_status', 'Can read all destinations')]},
        ),
    ]
