# Generated by Django 4.0.10 on 2023-09-16 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0006_alter_destination_options'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='destination',
            index=models.Index(fields=['id'], name='id_index'),
        ),
    ]
